repos:
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.8
    hooks:
      - id: clang-format
        files: "\\.(ino|pde|c|cc|cpp|cxx|h|hh|hpp)$"
        args: ["--style=file"]
