name: Build hardware firmware

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - fix/*

    tags:
      - "v*.*.*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install PlatformIO
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Build broker firmware
        shell: bash
        run: |
          cd src_broker_esp32
          platformio run -e esp32_broker

      - name: Build package firmware
        shell: bash
        run: |
          cd src_package_arduino
          platformio run -e uno_r4_wifi

      - name: Upload broker firmware/artifact
        uses: actions/upload-artifact@v4
        with:
          name: ESP32-broker
          path: src_broker_esp32/.pio/build/esp32_broker/firmware.bin

      - name: Upload sensor firmware/artifact
        uses: actions/upload-artifact@v4
        with:
          name: uno-r4-wifi
          path: src_package_arduino/.pio/build/uno_r4_wifi/firmware.bin

      - name: Tag status check
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "Tagged release detected. Proceeding with Zip and GitHub Release steps."

      - name: Zip firmware files
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          mkdir -p release
          cp src_broker_esp32/.pio/build/esp32_broker/firmware.bin release/esp32-broker.bin
          cp src_package_arduino/.pio/build/uno_r4_wifi/firmware.bin release/uno-r4-wifi.bin
          zip -j release/firmware-${GITHUB_REF#refs/tags/}.zip release/esp32-broker.bin release/uno-r4-wifi.bin

      - name: Upload firmware ZIP to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: release/firmware-${GITHUB_REF#refs/tags/}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
