name: Build hardware firmware

on:
  push:
    branches:
      - main
      - develop
      - feature/*
      - fix/*
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  build-push:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup PlatformIO environment
        uses: ./.github/workflows/setup-platformio

      - name: Build and lint firmware
        uses: ./.github/workflows/build-lint

      - name: Tag status check
        if: startsWith(github.ref, 'refs/tags/')
        run: echo "Tagged release detected. Proceeding with Zip and GitHub Release steps."

      - name: Zip firmware files
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          mkdir -p release
          cp src_broker_esp32/.pio/build/esp32_broker/firmware.bin release/esp32-broker.bin
          cp src_package_arduino/.pio/build/uno_r4_wifi/firmware.bin release/uno-r4-wifi.bin
          zip -j release/firmware.zip release/esp32-broker.bin release/uno-r4-wifi.bin

      - name: Upload firmware ZIP to GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: release/firmware.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup PlatformIO environment
        uses: ./.github/workflows/setup-platformio

      - name: Build and lint firmware
        uses: ./.github/workflows/build-lint

      - name: Upload broker firmware/artifact
        uses: actions/upload-artifact@v4
        with:
          name: ESP32-broker
          path: src_broker_esp32/.pio/build/esp32_broker/firmware.bin

      - name: Upload sensor firmware/artifact
        uses: actions/upload-artifact@v4
        with:
          name: uno-r4-wifi
          path: src_package_arduino/.pio/build/uno_r4_wifi/firmware.bin
