name: Build hardware firmware

on:
  push:
    branches:
      - main
      - develop
      - "*"
  pull_request:
    branches:
      - main
      - develop
      - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip

      - name: Cache PlatformIO packages
        uses: actions/cache@v4
        with:
          path: ~/.platformio

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install PlatformIO
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio

      - name: Build broker firmware
        shell: bash
        run: |
          cd src_broker_esp32
          platformio run

      - name: Build package firmware
        shell: bash
        run: |
          cd src_package_arduino
          platformio run
